// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using startProject.Data;

namespace startProject.Data.Migrations
{
    [DbContext(typeof(StartProjectContext))]
    [Migration("20200120174811_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("startProject.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("WeekNrFlowerEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekNrFlowerStart")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "krokus",
                            WeekNrFlowerEnd = 15,
                            WeekNrFlowerStart = 8
                        },
                        new
                        {
                            Id = 2,
                            Name = "narcis",
                            WeekNrFlowerEnd = 20,
                            WeekNrFlowerStart = 10
                        },
                        new
                        {
                            Id = 3,
                            Name = "hyacint",
                            WeekNrFlowerEnd = 30,
                            WeekNrFlowerStart = 15
                        },
                        new
                        {
                            Id = 4,
                            Name = "tulp",
                            WeekNrFlowerEnd = 40,
                            WeekNrFlowerStart = 25
                        },
                        new
                        {
                            Id = 5,
                            Name = "violet",
                            WeekNrFlowerEnd = 45,
                            WeekNrFlowerStart = 25
                        },
                        new
                        {
                            Id = 6,
                            Name = "roos",
                            WeekNrFlowerEnd = 42,
                            WeekNrFlowerStart = 30
                        },
                        new
                        {
                            Id = 7,
                            Name = "zonnebloem",
                            WeekNrFlowerEnd = 32,
                            WeekNrFlowerStart = 20
                        },
                        new
                        {
                            Id = 8,
                            Name = "margriet",
                            WeekNrFlowerEnd = 28,
                            WeekNrFlowerStart = 18
                        },
                        new
                        {
                            Id = 9,
                            Name = "goudsbloem",
                            WeekNrFlowerEnd = 30,
                            WeekNrFlowerStart = 20
                        },
                        new
                        {
                            Id = 10,
                            Name = "Clematis ",
                            WeekNrFlowerEnd = 35,
                            WeekNrFlowerStart = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
